include: package:lint/analysis_options.yaml
linter:
  rules:
    always_put_required_named_parameters_first: false
    prefer_single_quotes: true
    trailing_commas: true
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    unawaited_futures: true
    unused_element: false
analyzer:
  exclude:
    - assets/**/*.*