name: infrastucture
description: A simpl-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: "none"

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  # path: ^1.8.0
  json_annotation: ^4.3.0
  domain:
    path: ../domain
  common_dependencies:
    path: ../common_dependencies

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  lints: ^1.0.0
